### ISSUE TITLE
Enable automaticRecovery

### ISSUE THREAD

**Issue by dwettstein** [dwettstein/kairosdb-rabbitmq#2]
```bash
07-31|17:28:42.311 [Thread-13] ERROR [null:-1] - [KRMQ] An error occurred:
com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
        at com.rabbitmq.client.QueueingConsumer.handle(QueueingConsumer.java:201)
        at com.rabbitmq.client.QueueingConsumer.nextDelivery(QueueingConsumer.java:218)
        at org.kairosdb.plugin.rabbitmq.core.RabbitmqConsumer.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)
07-31|17:28:42.312 [Thread-13] INFO  [null:-1] - [KRMQ] Execution interrupted. Disconnecting from RabbitMQ broker.
```

```java
ConnectionFactory factory = new ConnectionFactory();
factory.setAutomaticRecoveryEnabled(true);
```
https://www.rabbitmq.com/api-guide.html

**Comment by dwettstein** [comment]
Implemented by 334c3fdaf54d1800e552ed495fa6bdd3b73842cf
